# Generated by Django 4.2.4 on 2023-08-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("inquiry_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Productname", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.CharField(max_length=100)),
                ("productID", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("user_first_name", models.CharField(max_length=50)),
                ("user_last_name", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_pages.product",
                    ),
                ),
            ],
        ),
    ]
