# Generated by Django 4.2.4 on 2023-08-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_pages", "0002_rename_productid_cart_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productLoc",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="productType",
            field=models.CharField(default="N/A", max_length=50),
        ),
    ]
