# Generated by Django 4.2.4 on 2023-08-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_pages", "0003_product_productloc_product_producttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productIMG",
            field=models.ImageField(blank=True, null=True, upload_to="media_cdn"),
        ),
    ]
