# Generated by Django 4.2.4 on 2023-08-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_pages", "0004_product_productimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productIMG",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
